name: "Electron Rebuild Testing"

on: [pull_request]

jobs:
  rebuild:
    name: Run electron-rebuild
    runs-on: ubuntu-slim
    strategy:
      matrix:
        node-version: [22.x, 24.x, 25.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install MagicMirror
        run: node --run install-mm
      - name: Install @electron/rebuild
        run: npm install @electron/rebuild
      - name: Install test library (serialport) to be rebuilt
        run: npm install serialport
      - name: Run electron-rebuild
        run: npx electron-rebuild
        continue-on-error: false
